### ISSUE TITLE
Presence-faker shouldn't "reset" if already running and input payload == true

### ISSUE THREAD

**Issue by RomRider** [csuermann/node-red-contrib-presence-faker#1]
Hey,

I'm using your node and it's really great!
One thing however I'd do differently is if the node is already active, sending an input payload with true shouldn't reset the node's "random" time.

Also, there should still be a method to reset the random timers every day. Currently, once the node is enabled, everyday the random times are the same.

Here it's should test if it's already active, and if it is, do nothing:
https://github.com/csuermann/presence-faker/blob/master/presence-faker.js#L156-L163

What do you think?

Cheers

**Comment by csuermann** [comment]
Hi @RomRider,

Please accept my apologies for coming back to you so damn late! 🙏 

The rescheduling upon each `TRUE` message is actually a feature. 😹 If you need to circumvent that, you could, for example, use an `rbe` (report by exception) node in front of the presence-faker node.

![image](https://user-images.githubusercontent.com/10939809/63104747-d5c94500-bf7f-11e9-8580-f33b31293a84.png)

Regarding your second point, I could not reproduce your problem of schedules not being re-created randomly the next day. In fact, a new random schedule should get created whenever a defined window begins.
