### ISSUE TITLE
feature request: sunrise/sunset as start/end window

### ISSUE THREAD

**Issue by paede81** [csuermann/node-red-contrib-presence-faker#10]
Can you please add sunrise/sunset/dusk/dawn based on longitude/latitude as start and/or end window?
This is for example useful, if you want to define start time based on sunset (because time of dusk is different in winter and summer) and it makes no sense if you set the start time of the window when the sun is still shining (eg. summer)

**Comment by csuermann** [comment]
Hi @paede81,

You can accomplish that quite easily by combining the presence-faker node with a [suncron](https://www.npmjs.com/package/node-red-contrib-suncron)-node, like so:

![image](https://user-images.githubusercontent.com/10939809/83248750-d6953580-a1a5-11ea-8480-8d46192e38dd.png)

Here is an importable [example flow](https://github.com/csuermann/node-red-contrib-presence-faker/files/4701123/flow.json.txt) for your convenience.

I hope that helps!

Best regards,
C.
