### ISSUE TITLE
Window Time Problem

### ISSUE THREAD

**Issue by valbuz** [csuermann/node-red-contrib-presence-faker#12]
hi

i have entered the time beetween the node is active(see picture)
but it switch's my bulb's also during the day!

![image](https://user-images.githubusercontent.com/35503440/85699422-cf494500-b6db-11ea-97d9-0eeb170073f9.png)
![image](https://user-images.githubusercontent.com/35503440/85699474-d96b4380-b6db-11ea-815c-8488931bbb68.png)

Vers.: 1.5.10

thanks
pat

**Comment by csuermann** [comment]
Hi @valbuz,

Thanks for reporting this!

Just to be sure: I see your presence-faker-node has incoming connections. Are you by any chance overriding the window configuration dynamically (e.g. windowBegin and windowEnd)?

Best regards
C.

**Comment by valbuz** [comment]
Thanks for reply.

This is only for testing. On and off are the inputs. No other config items.


Pat

**Comment by csuermann** [comment]
Thank you, @valbuz! You're the second person reporting this problem, yet I could not reproduce it so far. I just released v1.6.0 which introduces a checkbox in the editor to enable logging debug messages to the console. I hope to narrow down the issue by studying the logs, so if you could paste them here together with your node JSON, that would be much appreciated.

**Comment by csuermann** [comment]
I finally managed to reproduce the issue and fixed it in v.1.6.1.

Best regards
C.

**Comment by valbuz** [comment]
Hi
Sorry...
When i will trigger the presence activation with a sunset node, then i want to get the lamps on when the trigger starts.
But everytime the presence node starts with a OFF Event. So it can be, the lamps going on in a few hours after sunset...
is it possible to get start everytime with a ON Event?

thanks
pat

**Comment by csuermann** [comment]
That's actually a nice feature request (being able to select whether a schedule should start with an ON or OFF block). I will give it a shot when I have some spare time.

You could, of course, accomplish the desired behavior by flipping the messages for ON and OFF, e.g. set the ON payload to 'false' and the OFF payload to 'true'. It's a bit hacky but should work.

**Comment by csuermann** [comment]
@valbuz, I just released v1.7.0, which introduces the option to configure the type of the first and last block for a schedule:

![image](https://user-images.githubusercontent.com/10939809/86033627-87a71e00-ba39-11ea-8ea9-fc91db18888d.png)

I hope this is what you were looking for.

Best regards
C.

**Comment by valbuz** [comment]
Hi.

Sounds good :-)

i will try.

thanks a lot for the fast solution.

pat

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Mo., 29. Juni 2020 um 18:53 Uhr schrieb Cornelius Suermann <
notifications@github.com>:
