### ISSUE TITLE
time window spanning over midnight

### ISSUE THREAD

**Issue by praepoke** [csuermann/node-red-contrib-presence-faker#13]
Hello,
sorry for making another issue with this but i seems to have the same problem than Issue #9 . I use version 1.6.0 and if i set up a node that span over midnight, lots of time the schedule is messed up

here is a little debug hope it helps:

27 Jun 23:59:36 - [warn] [presence-faker:268e0a35.d9ee86] window crons deleted
[ { isOn: false, duration: 52053 },
{ isOn: true, duration: 12245 },
{ isOn: false, duration: 57835 },
{ isOn: true, duration: 9917 },
{ isOn: false, duration: 17350 } ]
27 Jun 23:59:36 - [warn] [presence-faker:268e0a35.d9ee86] installed new schedule with 4 blocks
27 Jun 23:59:36 - [warn] [presence-faker:268e0a35.d9ee86] [object Object],[object Object],[object Object],[object Object]
27 Jun 23:59:36 - [warn] [presence-faker:268e0a35.d9ee86] window crontabs set up for 22:30 and 05:00

28 Jun 00:00:41 - [warn] [presence-faker:268e0a35.d9ee86] window crons deleted
[ { isOn: false, duration: 44016 },
{ isOn: true, duration: 9433 },
{ isOn: false, duration: 79226 },
{ isOn: true, duration: 7923 },
{ isOn: false, duration: 8802 } ]
28 Jun 00:00:41 - [info] [debug:858c0788.4a6588]
{ topic: '', payload: false, _msgid: 'ae3df3a.9248a1' }
28 Jun 00:00:41 - [warn] [presence-faker:268e0a35.d9ee86] installed new schedule with 4 blocks
28 Jun 00:00:41 - [warn] [presence-faker:268e0a35.d9ee86] [object Object],[object Object],[object Object],[object Object]
28 Jun 00:00:41 - [warn] [presence-faker:268e0a35.d9ee86] window crontabs set up for 22:30 and 05:00

![image](https://user-images.githubusercontent.com/2188762/85933141-f4080d00-b8d3-11ea-9657-9601e2e705fc.png)

![image](https://user-images.githubusercontent.com/2188762/85933144-f79b9400-b8d3-11ea-92a0-dc278d121b19.png)

**Comment by csuermann** [comment]
Thanks for providing this log output. I finally managed to reproduce the issue and fixed it in v.1.6.1.

Best regards
C.
