### ISSUE TITLE
how check the time settings

### ISSUE THREAD

**Issue by valbuz** [csuermann/node-red-contrib-presence-faker#17]
hi
when i override the settings with input a object, where can i see the new values?
if i open the settings, i see always the time which i configure in the flow.

thanks
pat

![image](https://user-images.githubusercontent.com/35503440/90010275-e0f0a700-dc9f-11ea-97a9-ee81a76698bb.png)
![image](https://user-images.githubusercontent.com/35503440/90010330-f5cd3a80-dc9f-11ea-8ff8-442ce3a20aab.png)

**Comment by csuermann** [comment]
What is displayed in the editor is the default values the node will start up with. Any overridden configurations won't show up there. But it's a valid proposal to improve that behavior. I will think about it.
