### ISSUE TITLE
Feature Request: Indicate dynamically overridden settings in editor

### ISSUE THREAD

**Issue by csuermann** [csuermann/node-red-contrib-presence-faker#18]
I guess this is what needs to be used: https://nodered.org/docs/creating-nodes/node-js#exposing-settings-to-the-editor

https://github.com/csuermann/node-red-contrib-presence-faker/issues/17#issuecomment-672838084_

**Comment by valbuz** [comment]
again....
i have to raspi with node red and presence-faker running. both with the same version.
on one raspi it works since the update 1.8.0
on the other it doesn't work with the same flow.
see the att picture:
![right](https://user-images.githubusercontent.com/35503440/111529689-b9e0e300-8762-11eb-9ad1-236e68c0dc86.JPG)

![wrong](https://user-images.githubusercontent.com/35503440/111529499-84d49080-8762-11eb-8b76-9d4c4927d92e.JPG)

**Comment by csuermann** [comment]
Hi @valbuz,

could you please share the json export of both of your flows?

Also, what does the DevTools network tab show when you open the editor? It should look something like this:

![image](https://user-images.githubusercontent.com/10939809/111535777-c452ab00-8769-11eb-8897-020eaa4cf0c1.png)

**Comment by valbuz** [comment]
hi
here are the two flows.


[presence-faker_false.txt](https://github.com/csuermann/node-red-contrib-presence-faker/files/6162132/presence-faker_false.txt)
[presence-faker_working.txt](https://github.com/csuermann/node-red-contrib-presence-faker/files/6162133/presence-faker_working.txt)

**Comment by csuermann** [comment]
Your function node is composing a string instead of an object:

`msg.payload = '{"windowEnd":"' + sunrise + '"}';
`

Your working example converts that string back to JSON with a dedicated json node. Your failing example doesn't.

**Comment by valbuz** [comment]
so, i export the working nodes from working system and import it on the other system in a new flow. The same Node's work's only on the one system.....
Both systems have the same version's of Node Red/Presence-Faker.

This Flow works on one system and not on the other :-(
[flows.txt](https://github.com/csuermann/node-red-contrib-presence-faker/files/6163566/flows.txt)

**Comment by csuermann** [comment]
Can you please attach a debug-node behind the json-node and observe the payload received there?

**Comment by valbuz** [comment]
of course...

![sunrise](https://user-images.githubusercontent.com/35503440/111640658-ae41fa80-87fc-11eb-8e44-7e6cf2268f6d.PNG)

**Comment by csuermann** [comment]
Yap, there is the problem: It should be an object but is a string.

**Comment by valbuz** [comment]
.....i only export and import the flow on the other system...

**Comment by csuermann** [comment]
All I can tell you is that your sending the wrong message format to the presence-faker node. This is not a defect of presence-faker.

**Comment by valbuz** [comment]
Sorry, my error. i take the debug in front of the json-node :-)

Now the debug out as object...

![flow](https://user-images.githubusercontent.com/35503440/111680940-0855b680-8823-11eb-99cb-8ba2ec3eeb3a.JPG)

![object](https://user-images.githubusercontent.com/35503440/111680966-0f7cc480-8823-11eb-8f8e-af6f24770c8f.JPG)

![properties](https://user-images.githubusercontent.com/35503440/111681163-3e933600-8823-11eb-9c66-4e65901d5098.JPG)

**Comment by csuermann** [comment]
And the overridden settings still don't show up in the editor?

Which version of presence-faker do you use?

Once you override the settings, does the context-tab for the presence-faker node look similar to this?

![image](https://user-images.githubusercontent.com/10939809/111690332-58397b00-882d-11eb-87a6-49d23b60f1b9.png)

**Comment by valbuz** [comment]
![kontext](https://user-images.githubusercontent.com/35503440/111690803-f0cffb00-882d-11eb-94b7-9a64100b9597.JPG)

![version](https://user-images.githubusercontent.com/35503440/111690927-0e04c980-882e-11eb-8e86-665007dc6446.JPG)

the only difference on the two systems:  raspberry pi4 and the other is a Container on a Proxmox

pat

**Comment by csuermann** [comment]
Good to know. Maybe the call to the context API doesn't go through. Can you please check and compare the network tab?

https://github.com/csuermann/node-red-contrib-presence-faker/issues/18#issuecomment-801430094

**Comment by valbuz** [comment]
what's the url of the api call? there is nothing blocked in my proxmox (so i know)

**Comment by csuermann** [comment]
the URL contains the Node-RED node-ID at the end, in my case it looks like this: `http://rpi4.local:1880/context/node/13d3434b.54931d`

**Comment by valbuz** [comment]
The is no FW activ on my Container himself...
Also on another Container, it doesn't work. So it must be a problem with proxmox....

thanks
pat

**Comment by valbuz** [comment]
I change my last Raspi to a Proxmox and here it also stop's working :-(

Why isn't it possible to change the value's in the corresponding input forms himself?

![form](https://user-images.githubusercontent.com/35503440/111919622-30dfe980-8a8b-11eb-8dc8-bc613451df88.JPG)

**Comment by csuermann** [comment]
Have you made any progress figuring out what's blocking the calls to the context API on your Proxmox based systems?

Mind you, the override should still work, it's only the visual hint in the editor, that's not working properly.

Of course you can set new values via the input forms, but that always requires a re-deploy of your flow.

**Comment by valbuz** [comment]
Hi

No, i didn't find the solution

and Yes, i know it works also without the Popup ;-)
so with the kontext showing the settings are ok for me.

thanks
pat
