### ISSUE TITLE
enable via input message.payload

### ISSUE THREAD

**Issue by dquercus** [csuermann/node-red-contrib-presence-faker#19]
Hi,

I'm using your node (v. 1.7.0) on node-red (v. 1.0.6 via home-assistant) and everything works really good except the input to enable/disable the node based on an external variable.

I've added an inject node with 'TRUE' as message payload but still the presence-faker node does not get activated.

Image of the complete flow:
![image](https://user-images.githubusercontent.com/243210/90045079-d8639500-dcce-11ea-82fe-e82812788344.png)
How the injection is done:
![image](https://user-images.githubusercontent.com/243210/90045115-df8aa300-dcce-11ea-8c92-a13e4b2b68e3.png)
The presence-faker configuration:
![image](https://user-images.githubusercontent.com/243210/90045139-e6191a80-dcce-11ea-90b9-c788f4117ed7.png)
Example when I click on the inject but the presence-faker does not react ...
![image](https://user-images.githubusercontent.com/243210/90045193-f6c99080-dcce-11ea-8973-420559215eb3.png)

I'm missing anything?

Thanks in advance,
David.

**Comment by csuermann** [comment]
Hey @dquercus,

Looks like you tried the _one_ way of spelling the activation keyword which is not implemented. This is the respective [code](https://github.com/csuermann/node-red-contrib-presence-faker/blob/d955f752898d68e200937229d4ee06b6ca44092d/presence-faker.js#L194-L199):
```
msg.payload === true ||
msg.payload === 'true' ||
msg.payload === 'enable' ||
msg.payload === 'activate'
...
```

Hope that helps!

Best regards
Cornelius

**Comment by dquercus** [comment]
Yes! it worked. Thanks a lot!
