### ISSUE TITLE
Generate times near "begin" and "end" limits

### ISSUE THREAD

**Issue by JaviElio** [csuermann/node-red-contrib-presence-faker#2]
I have set up the node to generate a random trigger between 8:00 to 20:00 but the results are always between 11:00 to 17:00 ( more or less).

Looks like it is not possible to generate random times near the limits. 
Can this be improved?

Thanks in advace,

![Presence-faker node](https://user-images.githubusercontent.com/25644638/62557938-48e40480-b878-11e9-8d78-59f83637f7fc.png)

**Comment by csuermann** [comment]
Hi @JaviElio,

Thanks for the bug-report. I was able to reproduce the problem and just fixed it in v1.4.1.

Best regards
Cornelius
