### ISSUE TITLE
node-red docker exit after error "Cannot read property 'duration' of undefined"

### ISSUE THREAD

**Issue by dcast78** [csuermann/node-red-contrib-presence-faker#21]
Hi,
running node-red under docker stopped working with this error.
I cannot find debug log file under .npm, I hope this message is enough to understand the problem.

```
node-red    | 22 Aug 21:10:00 - [red] Uncaught Exception:
node-red    | 22 Aug 21:10:00 - TypeError: Cannot read property 'duration' of undefined
node-red    |     at createSchedule (/data/node_modules/node-red-contrib-presence-faker/pf.js:95:12)
node-red    |     at CronJob.windowBeginCronCallback (/data/node_modules/node-red-contrib-presence-faker/presence-faker.js:77:42)
node-red    |     at CronJob.fireOnTick (/data/node_modules/cron/lib/cron.js:600:23)
node-red    |     at Timeout.callbackWrapper [as _onTimeout] (/data/node_modules/cron/lib/cron.js:667:10)
node-red    |     at ontimeout (timers.js:436:11)
node-red    |     at tryOnTimeout (timers.js:300:5)
node-red    |     at listOnTimeout (timers.js:263:5)
node-red    |     at Timer.processTimers (timers.js:223:10)
node-red    | npm ERR! code ELIFECYCLE
node-red    | npm ERR! errno 1
node-red    | npm ERR! node-red-docker@1.0.6 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
node-red    | npm ERR! Exit status 1
node-red    | npm ERR! 
node-red    | npm ERR! Failed at the node-red-docker@1.0.6 start script.
node-red    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
node-red    | 
node-red    | npm ERR! A complete log of this run can be found in:
node-red    | npm ERR!     /data/.npm/_logs/2020-08-22T19_10_00_343Z-debug.log
node-red    | 
node-red    | > node-red-docker@1.0.6 start /usr/src/node-red
node-red    | > node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"
node-red    | 
node-red    | 22 Aug 21:10:04 - [trace] git["--version"]
node-red    | 22 Aug 21:10:04 - [trace] git["config","--global","user.name"]
node-red    | 22 Aug 21:10:04 - [trace] git["config","--global","user.email"]
node-red    | 22 Aug 21:10:04 - [info] 

```

**Comment by csuermann** [comment]
Hi @dcast78,

Can you please post your presence-faker node here? Thank you!

Best regards
Cornelius

**Comment by dcast78** [comment]
Uhm, I installed presence faker from node-red palette some time ago with version "1.5.10", yesterday after the problem I have updated to "1.7.1" and overwritten the files. 

I would also like to point out that the container has been active for some time, but the problem occurred only yesterday and maybe some other time when I was not able to analyze the log so it is probably a special case.

thanks

**Comment by csuermann** [comment]
The exception seems to stem from an edge case when the presence-faker node is configured with a lower limit of zero "ON times". Depending on the upper limit, this might only happen occasionally. Can you confirm that the problem might be related to this?

**Comment by dcast78** [comment]
This is my node config.

![immagine](https://user-images.githubusercontent.com/3026850/90984323-70d20300-e574-11ea-9bdb-a1efa144c328.png)

**Comment by csuermann** [comment]
Thanks for sharing your config. I believe v.1.7.2 should fix this error. However, I noted that your settings are probably impossible to fulfill as the upper limit of 1h can never fit into a window of only 40 minutes. ;-)
