### ISSUE TITLE
send "off" signals if cycle complete?

### ISSUE THREAD

**Issue by crackers8199** [csuermann/node-red-contrib-presence-faker#22]
if i have a cycle set to run from 10pm-8am, and the last switch sent before 8am was an "on" switch, the device remains turned on and will never be turned off until the next cycle. is there a way to set this up so that at the end of the cycle it always makes sure the devices are off? i don't want to have lights and other stuff turned on during the day when it's not necessary...

**Comment by crackers8199** [comment]
i'm guessing after doing some more searching that this is what the "first block" and "last block" options are for?

**Comment by csuermann** [comment]
Hi @crackers8199,
yes, indeed, "first block" and "last block" are the options that allow you to control exactly that.
Best regards
Cornelius

**Comment by crackers8199** [comment]
@csuermann is there a way to not always have it start with an "on" command? mine always seems to send the turn on at the beginning of the cycle...i've had it running the past three days and i have it tuned to almost exactly where i want it, but it is always turning all of the lights on at exactly the beginning of the cycle every night. anyone watching the house for an extended period would notice that it's not random in that respect...

**Comment by csuermann** [comment]
you can set "first block" to "OFF message" to achieve just that.
