### ISSUE TITLE
Feature request, and problem?

### ISSUE THREAD

**Issue by LucaV87** [csuermann/node-red-contrib-presence-faker#23]
Good morning,
it would be interesting to have the possibility to insert a list of entities (lights) that are switched on and off randomly ..
I also have a problem with making fake presence start when it gets "true" .. what am I wrong?
thanks

https://ibb.co/CsZP6HK
https://ibb.co/6Z44vKP
https://ibb.co/nB8H9MG

**Comment by csuermann** [comment]
Hi, did you double-check that your 'change node' really works as expected? The screenshots don't show what the debug-node actually received.
