### ISSUE TITLE
Begin time as payload?

### ISSUE THREAD

**Issue by Swiftnesses** [csuermann/node-red-contrib-presence-faker#3]
Hi,

I'd like to trigger this via my LUX sensors, i.e. when LUX < 400 trigger flow. It would be great (and logical in my opinion) if I could trigger the faker at x and set only an end time, i.e. 23:00. It would then do the magic based on the current window and other window settings.

Is this possible?

**Comment by csuermann** [comment]
Hi @Swiftnesses!
Thanks for your suggestion! Have you considered defining a broader static window for the presence-faker (e.g. 04:00 - 23:00) and just _activating_ the faker based on your LUX threshold?

**Comment by Swiftnesses** [comment]
That'll work, thanks @csuermann. The reason I didn't do this originally is I wanted strict control over the period and window settings...

**Comment by csuermann** [comment]
I also just released [v.1.5.0](https://www.npmjs.com/package/node-red-contrib-presence-faker/v/1.5.0), which allows you to overwrite the config dynamically by injecting an object like so:

```
{
    "windowBegin": "00:00",  //string
    "windowEnd": "23:59:59", //string
    "minDuration": 60,       //seconds as int
    "maxDuration": 600,      //seconds as int
    "minCount": 10,          //int
    "maxCount": 30           //int
}
```
