### ISSUE TITLE
Sunrise-Sunset options pleaseeee

### ISSUE THREAD

**Issue by Yonny24** [csuermann/node-red-contrib-presence-faker#34]
This is a great node. Just really missing the sunset/sunrise with offset options instead of fixed times.

I have to constantly adjust the times to compensate for the sunset.

Unless there is another option to add.

Please consider adding this option or point me in the right direction.

Many thanks

**Comment by csuermann** [comment]
Hi @Yonny24,

Have you considered combining the presence-faker node with the suncron node, as outlined [here](https://github.com/csuermann/node-red-contrib-presence-faker/issues/30#issuecomment-889001150)?

Best,
C.

**Comment by Yonny24** [comment]
I'll have a look at that first thanks. But would be ideal if the presence faker had this integrated options

**Comment by csuermann** [comment]
Feel free to send a PR ;-)

**Comment by Yonny24** [comment]
Sorry have not been able to work out how to inject dynamic times or from sun-cron.
Are you able to add sunset/offset to the window begin field in the node?

**Comment by Yonny24** [comment]
This json was just what I was looking for. I had invented another more complicated method but it stopped working.
Thank you.
[sunset](https://gist.github.com/csuermann/604f846f4b7bc3a518dc6385c16e3a48)
