### ISSUE TITLE
Wrong timings

### ISSUE THREAD

**Issue by ukrolelo** [csuermann/node-red-contrib-presence-faker#39]
The simulation is wrong, the on time that i put min 2 max 5 are not used as you can see in history.
This settings were with my last installation and worked fine. (nobody is at that place so cant turn on/off and only i have the app)

![Screenshot_236](https://user-images.githubusercontent.com/60402662/147057798-c198340a-0b0f-406f-bd49-3b494a796827.png)
![Screenshot_237](https://user-images.githubusercontent.com/60402662/147057803-d4ab6822-798e-44ea-8928-a852e96097cf.png)
![Screenshot_238](https://user-images.githubusercontent.com/60402662/147057812-f6481bd8-8136-4657-9d37-7f81fd84c5ca.png)
![Screenshot_239](https://user-images.githubusercontent.com/60402662/147057821-ef6c0c17-8d0a-46d3-a9d9-fb99a24cd5bd.png)
![Screenshot_240](https://user-images.githubusercontent.com/60402662/147057832-5d7a4f5e-d033-4e0f-b749-996117dcc76d.png)
![Screenshot_241](https://user-images.githubusercontent.com/60402662/147057849-da8f18b0-7172-463d-90f0-a130a4a7a3cb.png)

**Comment by csuermann** [comment]
Hi @ukrolelo,

Could you share the Node-RED debug output (logging toggle switched on in the presence-faker settings)?

**Comment by ukrolelo** [comment]
I have just realise that i have every minute injection and that might be the problem?

`12/22/2021, 8:42:21 PMnode: Bocni_svetlo
msg : string[20]
"window crons deleted"
12/22/2021, 8:42:21 PMnode: Bocni_svetlo
msg : string[23]
"2 message crons deleted"
12/22/2021, 8:42:21 PMnode: Vrchni_svetlo
msg : string[20]
"window crons deleted"
12/22/2021, 8:42:21 PMnode: Vrchni_svetlo
msg : string[23]
"3 message crons deleted"
12/22/2021, 8:42:21 PMnode: Vrchni_svetlo
msg : string[31]
"new node status: starting up..."
12/22/2021, 8:42:22 PMnode: Vrchni_svetlo
msg : string[35]
"new node status: inactive upon load"
12/22/2021, 8:42:28 PMnode: Vrchni_svetlo
msg : string[23]
"0 message crons deleted"
12/22/2021, 8:42:28 PMnode: Vrchni_svetlo
msg : string[22]
"isNowWithinWindow? Yes"
12/22/2021, 8:42:29 PMnode: Vrchni_svetlo
msg : string[33]
"executing windowBeginCronCallback"
12/22/2021, 8:42:30 PMnode: Vrchni_svetlo
msg : string[475]
"created new schedule: [{"isOn":true,"duration":5588,"beginString":"20:08:13","endString":"21:41:21","begin":"2021-12-22T19:08:13.000Z"},{"isOn":false,"duration":981,"beginString":"21:41:21","endString":"21:57:42","begin":"2021-12-22T20:41:21.000Z"},{"isOn":true,"duration":6848,"beginString":"21:57:42","endString":"23:51:50","begin":"2021-12-22T20:57:42.000Z"},{"isOn":false,"duration":490,"beginString":"23:51:50","endString":"00:00:00","begin":"2021-12-22T22:51:50.000Z"}]"
12/22/2021, 8:42:31 PMnode: Vrchni_svetlo
msg : string[129]
"executing block: {"isOn":true,"duration":5588,"beginString":"20:08:13","endString":"21:41:21","begin":"2021-12-22T19:08:13.000Z"}"
12/22/2021, 8:42:32 PMnode: Vrchni_svetlo
msg : string[41]
"new node status: ON [20:08:13 - 21:41:21]"
12/22/2021, 8:42:33 PMnode: Vrchni_svetlo
msg : string[28]
"installed crons for 3 blocks"
12/22/2021, 8:42:34 PMnode: Vrchni_svetlo
msg : string[42]
"window crontabs set up for 18:00 and 00:00"
12/22/2021, 8:43:28 PMnode: Vrchni_svetlo
msg : string[20]
"window crons deleted"
12/22/2021, 8:43:28 PMnode: Vrchni_svetlo
msg : string[23]
"3 message crons deleted"
12/22/2021, 8:43:28 PMnode: Vrchni_svetlo
msg : string[22]
"isNowWithinWindow? Yes"
12/22/2021, 8:43:28 PMnode: Vrchni_svetlo
msg : string[33]
"executing windowBeginCronCallback"
12/22/2021, 8:43:28 PMnode: Vrchni_svetlo
msg : string[476]
"created new schedule: [{"isOn":true,"duration":5245,"beginString":"20:03:55","endString":"21:31:20","begin":"2021-12-22T19:03:55.000Z"},{"isOn":false,"duration":859,"beginString":"21:31:20","endString":"21:45:39","begin":"2021-12-22T20:31:20.000Z"},{"isOn":true,"duration":6342,"beginString":"21:45:39","endString":"23:31:21","begin":"2021-12-22T20:45:39.000Z"},{"isOn":false,"duration":1719,"beginString":"23:31:21","endString":"00:00:00","begin":"2021-12-22T22:31:21.000Z"}]"
12/22/2021, 8:43:28 PMnode: Vrchni_svetlo
msg : string[129]
"executing block: {"isOn":true,"duration":5245,"beginString":"20:03:55","endString":"21:31:20","begin":"2021-12-22T19:03:55.000Z"}"
12/22/2021, 8:43:28 PMnode: Vrchni_svetlo
msg : string[41]
"new node status: ON [20:03:55 - 21:31:20]"
12/22/2021, 8:43:28 PMnode: Vrchni_svetlo
msg : string[28]
"installed crons for 3 blocks"
12/22/2021, 8:43:28 PMnode: Vrchni_svetlo
msg : string[42]
"window crontabs set up for 18:00 and 00:00"
12/22/2021, 8:44:28 PMnode: Vrchni_svetlo
msg : string[20]
"window crons deleted"
12/22/2021, 8:44:28 PMnode: Vrchni_svetlo
msg : string[23]
"3 message crons deleted"
12/22/2021, 8:44:28 PMnode: Vrchni_svetlo
msg : string[22]
"isNowWithinWindow? Yes"
12/22/2021, 8:44:28 PMnode: Vrchni_svetlo
msg : string[33]
"executing windowBeginCronCallback"
12/22/2021, 8:44:28 PMnode: Vrchni_svetlo
msg : string[477]
"created new schedule: [{"isOn":true,"duration":6439,"beginString":"20:16:47","endString":"22:04:06","begin":"2021-12-22T19:16:47.000Z"},{"isOn":false,"duration":1359,"beginString":"22:04:06","endString":"22:26:45","begin":"2021-12-22T21:04:06.000Z"},{"isOn":true,"duration":4236,"beginString":"22:26:45","endString":"23:37:21","begin":"2021-12-22T21:26:45.000Z"},{"isOn":false,"duration":1359,"beginString":"23:37:21","endString":"00:00:00","begin":"2021-12-22T22:37:21.000Z"}]"
12/22/2021, 8:44:28 PMnode: Vrchni_svetlo
msg : string[129]
"executing block: {"isOn":true,"duration":6439,"beginString":"20:16:47","endString":"22:04:06","begin":"2021-12-22T19:16:47.000Z"}"
12/22/2021, 8:44:28 PMnode: Vrchni_svetlo
msg : string[41]
"new node status: ON [20:16:47 - 22:04:06]"
12/22/2021, 8:44:28 PMnode: Vrchni_svetlo
msg : string[28]
"installed crons for 3 blocks"
12/22/2021, 8:44:28 PMnode: Vrchni_svetlo
msg : string[42]
"window crontabs set up for 18:00 and 00:00"
12/22/2021, 8:45:28 PMnode: Vrchni_svetlo
msg : string[20]
"window crons deleted"
12/22/2021, 8:45:28 PMnode: Vrchni_svetlo
msg : string[23]
"3 message crons deleted"
12/22/2021, 8:45:29 PMnode: Vrchni_svetlo
msg : string[22]
"isNowWithinWindow? Yes"
12/22/2021, 8:45:30 PMnode: Vrchni_svetlo
msg : string[33]
"executing windowBeginCronCallback"
12/22/2021, 8:45:31 PMnode: Vrchni_svetlo
msg : string[477]
"created new schedule: [{"isOn":true,"duration":6281,"beginString":"20:06:27","endString":"21:51:08","begin":"2021-12-22T19:06:27.000Z"},{"isOn":false,"duration":1670,"beginString":"21:51:08","endString":"22:18:58","begin":"2021-12-22T20:51:08.000Z"},{"isOn":true,"duration":4949,"beginString":"22:18:58","endString":"23:41:27","begin":"2021-12-22T21:18:58.000Z"},{"isOn":false,"duration":1113,"beginString":"23:41:27","endString":"00:00:00","begin":"2021-12-22T22:41:27.000Z"}]"
12/22/2021, 8:45:32 PMnode: Vrchni_svetlo
msg : string[129]
"executing block: {"isOn":true,"duration":6281,"beginString":"20:06:27","endString":"21:51:08","begin":"2021-12-22T19:06:27.000Z"}"
12/22/2021, 8:45:33 PMnode: Vrchni_svetlo
msg : string[41]
"new node status: ON [20:06:27 - 21:51:08]"
12/22/2021, 8:45:34 PMnode: Vrchni_svetlo
msg : string[28]
"installed crons for 3 blocks"
12/22/2021, 8:45:35 PMnode: Vrchni_svetlo
msg : string[42]
"window crontabs set up for 18:00 and 00:00"
12/22/2021, 8:46:28 PMnode: Vrchni_svetlo
msg : string[20]
"window crons deleted"
12/22/2021, 8:46:28 PMnode: Vrchni_svetlo
msg : string[23]
"3 message crons deleted"
12/22/2021, 8:46:29 PMnode: Vrchni_svetlo
msg : string[22]
"isNowWithinWindow? Yes"
12/22/2021, 8:46:30 PMnode: Vrchni_svetlo
msg : string[33]
"executing windowBeginCronCallback"
12/22/2021, 8:46:31 PMnode: Vrchni_svetlo
msg : string[364]
"created new schedule: [{"isOn":false,"duration":2793,"beginString":"20:02:04","endString":"20:48:37","begin":"2021-12-22T19:02:04.000Z"},{"isOn":true,"duration":4033,"beginString":"20:48:37","endString":"21:55:50","begin":"2021-12-22T19:48:37.000Z"},{"isOn":false,"duration":7450,"beginString":"21:55:50","endString":"00:00:00","begin":"2021-12-22T20:55:50.000Z"}]"
12/22/2021, 8:46:32 PMnode: Vrchni_svetlo
msg : string[130]
"executing block: {"isOn":false,"duration":2793,"beginString":"20:02:04","endString":"20:48:37","begin":"2021-12-22T19:02:04.000Z"}"
12/22/2021, 8:46:33 PMnode: Vrchni_svetlo
msg : string[42]
"new node status: OFF [20:02:04 - 20:48:37]"
12/22/2021, 8:46:34 PMnode: Vrchni_svetlo
msg : string[28]
"installed crons for 2 blocks"
12/22/2021, 8:46:35 PMnode: Vrchni_svetlo
msg : string[42]
"window crontabs set up for 18:00 and 00:00"
12/22/2021, 8:47:28 PMnode: Vrchni_svetlo
msg : string[20]
"window crons deleted"
12/22/2021, 8:47:28 PMnode: Vrchni_svetlo
msg : string[23]
"2 message crons deleted"
12/22/2021, 8:47:29 PMnode: Vrchni_svetlo
msg : string[22]
"isNowWithinWindow? Yes"
12/22/2021, 8:47:30 PMnode: Vrchni_svetlo
msg : string[33]
"executing windowBeginCronCallback"
12/22/2021, 8:47:31 PMnode: Vrchni_svetlo
msg : string[477]
"created new schedule: [{"isOn":true,"duration":5257,"beginString":"19:54:34","endString":"21:22:11","begin":"2021-12-22T18:54:34.000Z"},{"isOn":false,"duration":1597,"beginString":"21:22:11","endString":"21:48:48","begin":"2021-12-22T20:22:11.000Z"},{"isOn":true,"duration":5590,"beginString":"21:48:48","endString":"23:21:58","begin":"2021-12-22T20:48:48.000Z"},{"isOn":false,"duration":2282,"beginString":"23:21:58","endString":"00:00:00","begin":"2021-12-22T22:21:58.000Z"}]"
12/22/2021, 8:47:32 PMnode: Vrchni_svetlo
msg : string[129]
"executing block: {"isOn":true,"duration":5257,"beginString":"19:54:34","endString":"21:22:11","begin":"2021-12-22T18:54:34.000Z"}"
12/22/2021, 8:47:33 PMnode: Vrchni_svetlo
msg : string[41]
"new node status: ON [19:54:34 - 21:22:11]"
12/22/2021, 8:47:34 PMnode: Vrchni_svetlo
msg : string[28]
"installed crons for 3 blocks"
12/22/2021, 8:47:35 PMnode: Vrchni_svetlo
msg : string[42]
"window crontabs set up for 18:00 and 00:00"
12/22/2021, 8:48:28 PMnode: Vrchni_svetlo
msg : string[20]
"window crons deleted"
12/22/2021, 8:48:28 PMnode: Vrchni_svetlo
msg : string[23]
"3 message crons deleted"
12/22/2021, 8:48:29 PMnode: Vrchni_svetlo
msg : string[22]
"isNowWithinWindow? Yes"
12/22/2021, 8:48:30 PMnode: Vrchni_svetlo
msg : string[33]
"executing windowBeginCronCallback"
12/22/2021, 8:48:31 PMnode: Vrchni_svetlo
msg : string[699]
"created new schedule: [{"isOn":true,"duration":6096,"beginString":"19:23:46","endString":"21:05:22","begin":"2021-12-22T18:23:46.000Z"},{"isOn":false,"duration":22,"beginString":"21:05:22","endString":"21:05:44","begin":"2021-12-22T20:05:22.000Z"},{"isOn":true,"duration":5260,"beginString":"21:05:44","endString":"22:33:24","begin":"2021-12-22T20:05:44.000Z"},{"isOn":false,"duration":157,"beginString":"22:33:24","endString":"22:36:01","begin":"2021-12-22T21:33:24.000Z"},{"isOn":true,"duration":4950,"beginString":"22:36:01","endString":"23:58:31","begin":"2021-12-22T21:36:01.000Z"},{"isOn":false,"duration":89,"beginString":"23:58:31","endString":"00:00:00","begin":"2021-12-22T22:58:31.000Z"}]"
12/22/2021, 8:48:32 PMnode: Vrchni_svetlo
msg : string[129]
"executing block: {"isOn":true,"duration":6096,"beginString":"19:23:46","endString":"21:05:22","begin":"2021-12-22T18:23:46.000Z"}"
12/22/2021, 8:48:33 PMnode: Vrchni_svetlo
msg : string[41]
"new node status: ON [19:23:46 - 21:05:22]"
12/22/2021, 8:48:34 PMnode: Vrchni_svetlo
msg : string[28]
"installed crons for 5 blocks"
12/22/2021, 8:48:35 PMnode: Vrchni_svetlo
msg : string[42]
"window crontabs set up for 18:00 and 00:00"
`

**Comment by ukrolelo** [comment]
Changed from current state to state change, now it seems okay.
Sorry for false alarm @csuermann <3
![Screenshot_245](https://user-images.githubusercontent.com/60402662/147149298-b563b98d-85ad-4984-a639-abaf9ef258b5.png)

**Comment by csuermann** [comment]
Glad to hear you were able to resolve this issue! 🎉
