### ISSUE TITLE
Error: Unknown alias: nan

### ISSUE THREAD

**Issue by valbuz** [csuermann/node-red-contrib-presence-faker#47]
Hi
i'm detecting the following error when i want to activate the node:

Error: Unknown alias: nan

I doesn't change anything in my flow.

thanks for any help
Pat

Node: 1.8.5
Node-RED v2.2.2

**Comment by csuermann** [comment]
Hi @valbuz,
Could you please provide a screenshot and debug log / console output? Thank you!

**Comment by valbuz** [comment]
Hi.
thanks for answer.
After, restart the NR, it seem's to work again.
i will test it a time...

**Comment by csuermann** [comment]
Glad to hear a restart fixed it. Closing the issue for now. Feel free to reopen with more information should the problem persist.
