### ISSUE TITLE
How to install the nodes

### ISSUE THREAD

**Issue by SamBozman** [csuermann/node-red-contrib-presence-faker#52]
Thanks for you contribution to the open source neighborhood. You do provide a very comprehensive guide to using these nodes but I do not see any documentation on how to install the nodes. (or even where they are?)
I have tried google to find out how a node is installed, but I have not yet found anything all that helpful. 
Is it possible you could put a short ReadMe together that would explain how we recognize which files we need to install these nodes and how we actually do this through node-red?

Thank you for listening
Sam

**Comment by csuermann** [comment]
Hi @SamBozman,

You can install the node via the Node-RED palette manager with just one click.
