### ISSUE TITLE
suncron payload

### ISSUE THREAD

**Issue by almo604** [csuermann/node-red-contrib-presence-faker#63]
Could anyone please guide me on what should be filled in the payload field of suncron 2.1.4? Whatever example I import into node-red shows only an empty field and is of no real help to me.

I am somehow blocked in my mind.

Sorry, if this might get into the wrong area. It is my first post.

**Comment by csuermann** [comment]
The value of the payload is totally up to you and depends on your use-case.

**Comment by almo604** [comment]
Hi Cornelius,

I am kind of unsettled with suncron. Tried version 1.6.2 this morning and has success with injecting sunrise/set times into my flow.

Now I wanted to again manage my palettes and tried to re-install 1.6.2 but got what you can see in the enclosed pic.

How to set the location? No choice for payload. 

Am I completely misunderstanding what’s going on there?

Sorry for my bad English

Brgds

Aloism604

**Comment by csuermann** [comment]
Hi @almo604,

Please note that GitHub does not include attachments when replying via email. Could you please upload your picture via the GitHub web interface?

**Comment by almo604** [comment]
I am trying. I am not really using github.

Tks for the info

Brdgs

Alois

**Comment by csuermann** [comment]
Closing this issue as it is actually about another repository and further discussed [here](https://github.com/csuermann/node-red-contrib-suncron/issues/37).
